version: "3.8"
services:
 db:
  container_name: db
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=demo
  ports: 
      - 9921:3306
 app:
    restart: always
    depends_on:
      - db
    build: ./
    ports:
      - 8888:7072
    
    
      
        
        
      
      